const app=document.querySelector('#app'),toastEl=document.querySelector('#toast');
const API_BASE=(window.HERO_CLASH_API||localStorage.getItem('hero_clash_api')||'').replace(/\/$/,'');
let paymentOrder=null;
const KEY='hero_clash_v4';
const defaults={coins:12480,gems:24,energy:12,maxEnergy:20,xp:240,level:12,xpNeed:300,wins:0,battles:0,zone:0,stage:1,unlockedZone:0,unlockedStage:3,daily:null,streak:0,claimedQuest:[],heroLevels:{lumi:12,roxy:10,nox:9,blitz:7}};
let state=load(),screen='home',battle=null;
const heroes={lumi:{name:'Lumi',role:'Mage',rarity:'LEGENDARY',power:180,art:'./assets/heroes/lumi.webp',fallback:'🧙‍♀️'},roxy:{name:'Roxy',role:'Rogue',rarity:'EPIC',power:195,art:'./assets/heroes/roxy.webp',fallback:'🦊'},nox:{name:'Nox',role:'Tank',rarity:'MYTHIC',power:220,art:'./assets/heroes/nox.webp',fallback:'🧛'},blitz:{name:'Blitz',role:'Warrior',rarity:'LEGENDARY',power:205,art:'./assets/heroes/blitz.webp',fallback:'🤖'}};
const zones=[['🌲','Neon Forest','The neon frontier'],['🏜️','Golden Desert','Ancient machines'],['❄️','Ice Kingdom','Frozen citadel'],['🌋','Lava World','Extreme danger'],['🌌','Space City','Final sector']];
const skills=[['⚔️','Strike',110,0],['💥','Blast',190,2],['⚡','Lightning',260,3],['☄️','Ultimate',430,5]];
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(x){toastEl.textContent=x;toastEl.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>toastEl.classList.remove('show'),2200)}
function power(id){return heroes[id].power+(state.heroLevels[id]-1)*35}function totalPower(){return Object.keys(heroes).reduce((a,k)=>a+power(k),0)}
function xp(n){state.xp+=n;while(state.xp>=state.xpNeed){state.xp-=state.xpNeed;state.level++;state.xpNeed=Math.floor(state.xpNeed*1.18);toast('🎉 Level '+state.level)}}
function img(h,cls=''){return `<div class="${cls}" style="background-image:linear-gradient(180deg,transparent 50%,#080811cc),url('${h.art}')" onerror="this.style.backgroundImage='none';this.textContent='${h.fallback}'"></div>`}
function header(){return `<header class="top"><div class="logo">HERO <i>CLASH</i></div><button class="wallet" data-a="wallet">🔗 WALLET</button></header>`}
function nav(){return `<nav class="nav">${[['home','🏠','Home'],['map','🗺️','World'],['heroes','👑','Heroes'],['rewards','🎁','Rewards'],['shop','🛒','Shop']].map(x=>`<button class="${screen===x[0]?'active':''}" data-s="${x[0]}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav>`}
function home(){let h=heroes.lumi;return `<main class="page"><section class="card hero"><div class="eyebrow">SEASON 01 • NEON RISE</div><h1>${h.name}</h1><div class="muted">${h.role} • LVL ${state.heroLevels.lumi}</div><div class="power">⚔ POWER ${power('lumi')}</div><div class="xp"><div class="xphead"><span>ACCOUNT LVL ${state.level}</span><span>${state.xp}/${state.xpNeed} XP</span></div><div class="bar"><i style="width:${state.xp/state.xpNeed*100}%"></i></div></div><button class="play" data-a="play">⚔️ PLAY BATTLE</button></section><div class="stats"><div class="card stat"><b>🪙 ${state.coins.toLocaleString()}</b><span>Coins</span></div><div class="card stat"><b>💎 ${state.gems}</b><span>Gems</span></div><div class="card stat"><b>⚡ ${state.energy}/${state.maxEnergy}</b><span>Energy</span></div></div><div class="title"><h2>🔥 Season Event</h2><span>LIVE</span></div><section class="card item"><div class="ico">⚡</div><div class="itemmain"><b>Neon Clash</b><small>Win battles and collect seasonal rewards</small></div><button class="smallbtn" data-s="map">PLAY</button></section><div class="title"><h2>📜 Daily Quest</h2><span>${state.wins}/5 wins</span></div><section class="card item"><div class="ico">🏆</div><div class="itemmain"><b>First Blood</b><small>Win 5 battles • reward 500 Coins</small></div></section></main>`}
function map(){return `<main class="page"><div class="title"><h2>🗺️ World Map</h2><span>${state.unlockedZone+1}/5</span></div>${zones.map((z,i)=>{let open=i<=state.unlockedZone;return `<section class="card zone" style="opacity:${open?1:.4}"><div class="icon">${z[0]}</div><h3>${z[1]}</h3><p>${open?z[2]:'🔒 Locked'}</p>${open?`<div class="stages">${[1,2,3,4,5].map(n=>{let ok=i<state.unlockedZone||n<=state.unlockedStage;return `<button class="stage ${i===state.zone&&n===state.stage?'on':''}" ${ok?'':'disabled'} data-a="stage" data-z="${i}" data-n="${n}">${ok?n:'🔒'}</button>`}).join('')}</div>`:''}</section>`}).join('')}</main>`}
function heroesPage(){return `<main class="page"><div class="title"><h2>👑 Heroes</h2><span>POWER ${totalPower()}</span></div><div class="grid">${Object.entries(heroes).map(([id,h])=>{let lv=state.heroLevels[id],cost=lv*500;return `<section class="card heroCard"><div class="portrait" style="background-image:linear-gradient(180deg,transparent 40%,#080811ee),url('${h.art}')">${h.fallback}</div><div class="tag">${h.rarity}</div><h3>${h.name}</h3><div class="muted">${h.role} • LVL ${lv}</div><div class="row" style="margin-top:10px"><b>⚔ ${power(id)}</b><button class="smallbtn" data-a="upgrade" data-h="${id}">⬆ ${cost} 🪙</button></div></section>`}).join('')}</div></main>`}
function rewards(){let d=new Date().toISOString().slice(0,10);let claimed=state.daily===d;return `<main class="page"><div class="title"><h2>🎁 Rewards</h2><span>STREAK ${state.streak}</span></div><div class="list"><section class="card item"><div class="ico">🎁</div><div class="itemmain"><b>Daily Reward</b><small>+1000 Coins +5 Gems</small></div><button class="smallbtn" data-a="daily" ${claimed?'disabled':''}>${claimed?'CLAIMED':'CLAIM'}</button></section><section class="card item"><div class="ico">🏆</div><div class="itemmain"><b>Battle Marathon</b><small>10 wins → +15 Gems</small></div><button class="smallbtn" data-a="marathon" ${state.wins<10?'disabled':''}>CLAIM</button></section><section class="card item"><div class="ico">⚡</div><div class="itemmain"><b>Free Energy</b><small>+5 energy once per account</small></div><button class="smallbtn" data-a="freeenergy">GET</button></section></div></main>`}
function shop(){const packs=[['gems100','💎','100 Gems','0.5 GRAM / 1 USDT','100'],['gems550','💎','550 Gems','2.2 GRAM / 5 USDT','550'],['gems1200','💎','1 200 Gems','4.5 GRAM / 10 USDT','1 200'],['gems2500','💎','2 500 Gems','8.5 GRAM / 20 USDT','2 500']];return `<main class="page"><div class="title"><h2>🛒 Neon Shop</h2><span>CRYPTO ONLY</span></div><section class="card payHero"><div class="payGlow"></div><div class="eyebrow">PREMIUM ECONOMY</div><h1>GET GEMS</h1><p>Моментальная выдача после подтверждения транзакции.</p></section><div class="list">${packs.map((x,i)=>`<section class="card pack"><div class="packIcon">${x[1]}</div><div class="itemmain"><b>${x[2]}</b><small>${i===0?'Стартовый набор':i===1?'🔥 +10% BONUS':i===2?'👑 +20% BONUS':'💥 MEGA PACK'} • ${x[3]}</small></div><div class="packBtns"><button class="paybtn gram" data-a="createOrder" data-product="${x[0]}" data-method="gram">GRAM</button><button class="paybtn usdt" data-a="createOrder" data-product="${x[0]}" data-method="usdt">USDT</button></div></section>`).join('')}</div><div class="title"><h2>💳 Оплата</h2><span>2 NETWORKS</span></div><section class="card payInfo"><div><b>💎 GRAM (TON)</b><small>${escapeHtml('UQAZ3funj_qRm0ZN6N6KK35zSL4gYPkxRjTX_QsOKi_8oRBw')}</small></div><div><b>₮ USDT (BEP20)</b><small>${escapeHtml('0xa3CD09200F8A0e8dBd27e0dE56a1B1CF9b14EbD2')}</small></div></section></main>`}
function paymentPage(){if(!paymentOrder)return `<main class="page"><section class="card result"><div class="big">💳</div><h1>PAYMENT</h1><p class="muted">Выбери набор в магазине.</p><button class="play" data-s="shop">BACK TO SHOP</button></section></main>`;const gram=paymentOrder.method==='gram';return `<main class="page"><div class="title"><h2>💳 Payment</h2><span>${paymentOrder.id}</span></div><section class="card paymentCard"><div class="paymentMethod">${gram?'💎 GRAM (TON)':'₮ USDT (BEP20)'}</div><div class="amountBig">${paymentOrder.amount} ${gram?'GRAM':'USDT'}</div><div class="payStatus">⏳ ОЖИДАЕТ ОПЛАТУ</div><div class="addressBox"><small>АДРЕС ПОЛУЧАТЕЛЯ</small><code>${escapeHtml(paymentOrder.recipient)}</code><button class="copyBtn" data-a="copyAddress">COPY ADDRESS</button></div>${gram?`<button class="play" data-a="openGram">💎 ОПЛАТИТЬ GRAM</button><button class="full" data-a="verifyGram">🔎 ПРОВЕРИТЬ ОПЛАТУ</button><p class="hint">Сумма уникальная для заказа. После отправки подожди несколько секунд и нажми проверку.</p>`:`<div class="hashBox"><input id="txHash" class="txInput" placeholder="Вставь TX HASH 0x..." autocomplete="off" spellcheck="false"><button class="play" data-a="verifyUsdt">₮ ПРОВЕРИТЬ USDT</button></div><p class="hint">Отправляй именно USDT по сети BNB Smart Chain (BEP20).</p>`}<button class="full" data-s="shop">← НАЗАД В МАГАЗИН</button></section></main>`}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function battlePage(){if(!battle)return '<main class="page"><div class="card item">Select a level on the map.</div></main>';let pp=Math.max(0,battle.php/battle.pmax*100),ep=Math.max(0,battle.ehp/battle.emax*100);return `<main class="page"><div class="title"><h2>⚔️ Battle</h2><span>${zones[battle.z][1]} • ${battle.n}</span></div><section class="card battle"><div class="row"><div class="hp"><div class="hphead"><span>YOU</span><b>${battle.php}</b></div><div class="hpbar"><i style="width:${pp}%"></i></div></div><b class="vs">VS</b><div class="hp enemy"><div class="hphead"><span>ENEMY</span><b>${battle.ehp}</b></div><div class="hpbar"><i style="width:${ep}%"></i></div></div></div><div class="fighters"><div class="fighter"><div class="avatar">🧙‍♀️</div><small>Lumi</small></div><div class="vs">VS</div><div class="fighter enemy"><div class="avatar">👹</div><small>Boss</small></div></div><div class="skills">${skills.map((s,i)=>`<button class="skill" data-a="skill" data-i="${i}" ${battle.lock||battle.cd[i]?'disabled':''}><strong>${s[0]}</strong>${battle.cd[i]?'CD '+battle.cd[i]:s[1]}</button>`).join('')}</div></section></main>`}
function result(){let win=battle.result==='win';return `<main class="page"><section class="card result"><div class="big">${win?'🏆':'💀'}</div><h1>${win?'VICTORY':'DEFEAT'}</h1><p class="muted">${win?'Stage cleared successfully.':'Upgrade your heroes and try again.'}</p>${win?`<div class="pills"><div class="pill">🪙 +${battle.rc}</div><div class="pill">💎 +${battle.rg}</div><div class="pill">⭐ +${battle.rx}</div></div>`:''}<button class="play" data-a="continue">${win?'CONTINUE':'BACK TO MAP'}</button></section></main>`}
function render(){let body={home,map,heroes:heroesPage,rewards,shop,payment:paymentPage,battle:battlePage,result}[screen]();app.innerHTML=header()+body+nav()}
function start(z=state.zone,n=state.stage){if(state.energy<1){toast('⚡ Not enough energy');return}state.energy--;save();let d=1+z*.45+(n-1)*.12;battle={z,n,pmax:Math.floor(1000+totalPower()*.45),php:Math.floor(1000+totalPower()*.45),emax:Math.floor(900*d),ehp:Math.floor(900*d),cd:[0,0,0,0],lock:false};screen='battle';render()}
function actSkill(i){if(!battle||battle.lock)return;if(battle.cd[i])return toast('⏱ Cooldown');battle.lock=true;let dmg=Math.floor(skills[i][2]*(1+totalPower()/5000)*(0.9+Math.random()*.2));battle.ehp=Math.max(0,battle.ehp-dmg);for(let j=0;j<4;j++)battle.cd[j]=Math.max(0,battle.cd[j]-1);battle.cd[i]=skills[i][3];if(battle.ehp<=0)return win();render();setTimeout(()=>{if(!battle)return;let dmg=Math.floor(70+battle.z*20+battle.n*9+Math.random()*45);battle.php=Math.max(0,battle.php-dmg);if(battle.php<=0)return lose();battle.lock=false;render()},500)}
function win(){let rc=350+battle.z*150+battle.n*80,rg=Math.random()<.25?1:0,rx=90+battle.z*25+battle.n*10;state.coins+=rc;state.gems+=rg;state.wins++;state.battles++;xp(rx);if(state.stage<5)state.stage++;else if(state.zone<4){state.zone++;state.stage=1;state.unlockedZone=Math.max(state.unlockedZone,state.zone);state.unlockedStage=1}state.unlockedStage=Math.max(state.unlockedStage,state.stage);save();Object.assign(battle,{result:'win',rc,rg,rx});screen='result';render()}
function lose(){state.battles++;save();battle.result='lose';screen='result';render()}
async function api(path,body){if(!API_BASE)return Promise.reject(new Error('Payment server is not configured'));const tg=window.Telegram?.WebApp;const initData=tg?.initData||'';const r=await fetch(API_BASE+path,{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Init-Data':initData},body:JSON.stringify({...body,initData})});const j=await r.json().catch(()=>({ok:false,error:'Bad server response'}));if(!r.ok||!j.ok)throw new Error(j.error||'Server error');return j}
async function createOrder(e){try{toast('⏳ Создаём заказ...');const j=await api('/api/order/create',{product:e.dataset.product,method:e.dataset.method});paymentOrder=j.order;screen='payment';render()}catch(err){toast('❌ '+err.message)}}
async function verifyGram(){try{toast('🔎 Ищем транзакцию...');const j=await api('/api/order/verify-ton',{orderId:paymentOrder.id});if(j.paid){state.gems+=j.gems;save();toast('💎 +'+j.gems+' Gems');paymentOrder=null;screen='shop';render()}else toast('⏳ '+j.message)}catch(err){toast('❌ '+err.message)}}
async function verifyUsdt(){const input=document.querySelector('#txHash');const txHash=input?.value.trim();if(!txHash)return toast('Вставь TX HASH');try{toast('🔎 Проверяем BSC...');const j=await api('/api/order/verify-usdt',{orderId:paymentOrder.id,txHash});if(j.paid){state.gems+=j.gems;save();toast('💎 +'+j.gems+' Gems');paymentOrder=null;screen='shop';render()}else toast('⏳ '+j.message)}catch(err){toast('❌ '+err.message)}}
async function copyAddress(){try{await navigator.clipboard.writeText(paymentOrder.recipient);toast('📋 Адрес скопирован')}catch{toast('Не удалось скопировать')}}
function openGram(){if(!paymentOrder?.tonUri)return;window.location.href=paymentOrder.tonUri}
const actions={play:()=>start(),stage:e=>{state.zone=+e.dataset.z;state.stage=+e.dataset.n;save();start(state.zone,state.stage)},skill:e=>actSkill(+e.dataset.i),upgrade:e=>{let id=e.dataset.h,c=state.heroLevels[id]*500;if(state.coins<c)return toast('🪙 Not enough Coins');state.coins-=c;state.heroLevels[id]++;save();toast('⬆️ '+heroes[id].name+' upgraded');render()},daily:()=>{let d=new Date().toISOString().slice(0,10);if(state.daily===d)return;state.daily=d;state.streak++;state.coins+=1000;state.gems+=5;save();toast('🎁 Daily reward claimed');render()},marathon:()=>{if(state.wins<10)return;state.wins-=10;state.gems+=15;save();toast('🏆 +15 Gems');render()},freeenergy:()=>{if(state.freeClaimed)return toast('Already claimed');state.freeClaimed=true;state.energy=Math.min(state.maxEnergy,state.energy+5);save();toast('⚡ +5 Energy');render()},chest:()=>{if(state.coins<1500)return toast('🪙 Not enough Coins');state.coins-=1500;let r=500+Math.floor(Math.random()*1500);state.coins+=r;if(Math.random()<.2)state.gems+=5;save();toast('📦 Chest opened');render()},energy:()=>{if(state.coins<500)return toast('🪙 Not enough Coins');state.coins-=500;state.energy=Math.min(state.maxEnergy,state.energy+20);save();toast('⚡ +20 Energy');render()},createOrder:e=>createOrder(e),copyAddress,openGram,verifyGram,verifyUsdt,wallet:()=>toast('🔗 Wallet connection will be added next'),continue:()=>{if(battle?.result==='win')return start(state.zone,state.stage);screen='map';render()}};
document.addEventListener('click',e=>{let x=e.target.closest('[data-s]');if(x){screen=x.dataset.s;render();return}x=e.target.closest('[data-a]');if(x&&actions[x.dataset.a])actions[x.dataset.a](x)});
const tg=window.Telegram?.WebApp;if(tg){try{tg.ready();tg.expand();tg.setHeaderColor('#080811');tg.setBackgroundColor('#080811')}catch{}}
render();
